[build]
    publish = "dist/angular-capacitor"
    command = "ng build"
    functions = "./netlify/functions"

[dev]
    targetPort = 4200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

